[phases.setup]
nixPkgs = ["chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python app.py"

[variables]
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"